package io.enerdstone.vertxmicroservice.shared.constant

const val FILE = "file"
const val HOCON = "hocon"
const val CONF = "conf"
const val PATH = "path"
const val DEFAULT_CONF_FILE = "conf/service-dev.conf"
const val SERVICE = "service"
const val KEYCLOAK = "keycloak"
const val USERNAME = "username"
const val PASSWORD = "password"
const val USER = "user"
const val EXPIRES_IN = "expires_in"
const val ACCESS_TOKEN = "access_token"
const val APPLICATION_JSON = "application/json"
const val ACCEPT = "Accept"
const val CONTENT_TYPE = "Content-Type"
const val ROCKSDB = "rocksdb"
const val SHARED_EXCEPTION_STATE = "sharedExceptionState"
const val SHARED_APPLICATION_STATE = "sharedApplicationState"
const val DEFAULT_CIRCUIT_BREAKER_NAME = "application-circuit-breaker"
const val CIRCUIT_BREAKER = "circuitBreaker"
